language: node_js

node_js:
- "stable"

install:
- npm install

cache:
  directories:
  - "node_modules"

script:
- npm run build-app

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist-demo
  on:
    branch: main
