name: vscroll-native build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      cause:
        description: 'Cause'
        required: true
        default: 'Manual triggering'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:

      - name: Dispatched?
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "This is dispatched"
          echo "Build reason: ${{ github.event.inputs.cause }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm test
      - run: npm run build
      - run: npm run build-app

      - name: Set output (branch name)
        id: vars
        run: echo ::set-output name=branch::${GITHUB_REF#refs/*/}

      - name: Skip Deploy?
        if: ${{ github.event_name != 'push' || steps.vars.outputs.branch != 'main' }}
        run: |
          echo "Only pushing to 'main' causes deploy automatically. Pushed to '${{ steps.vars.outputs.branch }}'"

      - name: Deploy
        if: ${{ github.event_name == 'push' && steps.vars.outputs.branch == 'main' }}
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist-demo
