name: vscroll-native manual deploy demo

on:
  workflow_dispatch:
    inputs:
      cause:
        description: 'Cause of run'
        required: true
        default: 'Manual triggering'

jobs:

  deploy-on-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build-app

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist-demo
